bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part22   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part22   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part40   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part40   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part29   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part29   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part11   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part11   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part103   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part103   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part89   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part89   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part82   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part82   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part111   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part111   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part115   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part115   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part131   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part131   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part94   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part94   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part71   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part71   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part34   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part34   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part76   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part76   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part126   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part126   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part41   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part41   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part27   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part27   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part3   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part3   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part67   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part67   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part24   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part24   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part117   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part117   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part5   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part5   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part127   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part127   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part81   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part81   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part72   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part72   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part18   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part18   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part30   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part30   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part108   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part108   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part9   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part9   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part119   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part119   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part106   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part106   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part130   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part130   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part25   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part25   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part53   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part53   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part72   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part72   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part42   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part42   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part93   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part93   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part32   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part32   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part53   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part53   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part1   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part1   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part16   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part16   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part43   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part43   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part1   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part1   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part58   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part58   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part73   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part73   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part113   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part113   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part52   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part52   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part12   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part12   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part83   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part83   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part97   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part97   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part79   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part79   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part113   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part113   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part84   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part84   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part77   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part77   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part0   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part0   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part112   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part112   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part18   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part18   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part56   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part56   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part98   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part98   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part19   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part19   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part85   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part85   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part4   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part4   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part107   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part107   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part66   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part66   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part102   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part102   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part8   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part8   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part31   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part31   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part47   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part47   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part50   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part50   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part88   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part88   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part7   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part7   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part86   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part86   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part117   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part117   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part26   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part26   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part65   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part65   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part6   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part6   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part75   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part75   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part119   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part119   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part94   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part94   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part57   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part57   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part50   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part50   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part76   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part76   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part121   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part121   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part64   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part64   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part100   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part100   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part58   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part58   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part100   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part100   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part27   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part27   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part45   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part45   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part15   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part15   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part95   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part95   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part118   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part118   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part74   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part74   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part97   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part97   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part46   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part46   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part101   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part101   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part86   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part86   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part46   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part46   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part13   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part13   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part87   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part87   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part0   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part0   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part14   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part14   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part14   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part14   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part71   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part71   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part90   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part90   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part55   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part55   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part43   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part43   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part34   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part34   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part95   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part95   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part110   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part110   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part2   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part2   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part35   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part35   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part124   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part124   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part25   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part25   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part26   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part26   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part92   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part92   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part11   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part11   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part73   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part73   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part105   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part105   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part61   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part61   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part70   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part70   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part51   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part51   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part85   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part85   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part122   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part122   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part28   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part28   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part60   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part60   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part104   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part104   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part93   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part93   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part66   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part66   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part36   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part36   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part57   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part57   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part83   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part83   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part17   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part17   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part21   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part21   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part36   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part36   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part62   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part62   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part10   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part10   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part101   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part101   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part65   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part65   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part20   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part20   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part23   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part23   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part51   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part51   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part30   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part30   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part81   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part81   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part39   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part39   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part68   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part68   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part98   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part98   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part112   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part112   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part45   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part45   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part96   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part96   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part77   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part77   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part80   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part80   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part63   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part63   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part20   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part20   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part123   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part123   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part44   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part44   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part116   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part116   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part33   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part33   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part29   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part29   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part12   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part12   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part5   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part5   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part17   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part17   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part92   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part92   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part9   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part9   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part38   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part38   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part62   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part62   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part106   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part106   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part68   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part68   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part102   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part102   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part120   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part120   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part103   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part103   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part88   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part88   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part84   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part84   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part49   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part49   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part107   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part107   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part63   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part63   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part104   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part104   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part35   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part35   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part54   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part54   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part89   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part89   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part3   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part3   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part116   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part116   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part21   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part21   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part31   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part31   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part69   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part69   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part4   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part4   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part59   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part59   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part132   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part132   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part10   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part10   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part48   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part48   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part56   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part56   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part37   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part37   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part125   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part125   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part40   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part40   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part82   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part82   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part67   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part67   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part37   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part37   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part16   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part16   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part24   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part24   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part28   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part28   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part64   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part64   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part52   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part52   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part33   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part33   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part90   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part90   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part42   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part42   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part79   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part79   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part60   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part60   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part8   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part8   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part23   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part23   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part78   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part78   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part59   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part59   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part80   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part80   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part39   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part39   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part105   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part105   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part99   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part99   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part15   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part15   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part87   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part87   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part96   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part96   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part120   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part120   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part54   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part54   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part75   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part75   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part108   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part108   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part2   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part2   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part111   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part111   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part133   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part133   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part48   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part48   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part91   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part91   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part91   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part91   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part70   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part70   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part22   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part22   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part69   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part69   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part61   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part61   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part114   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part114   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part41   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part41   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part110   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part110   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part129   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part129   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part38   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part38   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part6   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part6   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part19   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part19   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part44   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part44   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part49   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part49   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part128   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part128   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part99   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part99   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part114   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part114   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part78   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part78   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part13   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part13   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part109   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part109   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part32   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part32   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part74   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part74   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part55   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part55   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part118   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part118   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part109   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part109   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part7   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part7   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part115   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  DYJetsToLL_M-50__part115   ele
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part47   mu
bsub -q 2nd -u alvareza submit_batch_FR.sh  WJetsToLNu-LO__part47   ele
