bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part40    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part29    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part11    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part103    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part111    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part131    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part94    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part76    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part126    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part41    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part3    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part24    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part117    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part5    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part127    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part81    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part18    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part119    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part106    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part130    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part53    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part72    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part32    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part43    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part1    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part113    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part52    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part83    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part79    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part84    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part0    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part112    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part56    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part107    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part66    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part8    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part31    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part47    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part86    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part26    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part75    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part57    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part50    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part121    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part64    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part58    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part100    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part27    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part15    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part74    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part97    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part101    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part46    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part87    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part14    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part71    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part34    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part95    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part110    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part2    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part124    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part25    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part73    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part61    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part51    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part85    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part122    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part60    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part93    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part36    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part17    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part21    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part10    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part65    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part30    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part68    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part98    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part45    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part77    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part20    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part123    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part12    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part92    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part9    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part38    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part62    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part102    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part88    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part63    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part104    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part35    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part89    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part116    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part4    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part132    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part37    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part125    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part82    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part67    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part16    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part28    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part33    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part90    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part42    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part23    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part59    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part80    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part39    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part105    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part99    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part96    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part120    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part54    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part108    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part133    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part48    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part91    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part70    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part22    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part69    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part114    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part129    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part6    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part19    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part44    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part49    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part128    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part78    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part13    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part55    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part118    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part109    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part7    
bsub -q 2nd -u alvareza submit_batch_FR_Z.sh  DYJetsToLL_M-50__part115    
