bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part11.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part11.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part22.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part22.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part40.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part40.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part29.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part29.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part11.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part11.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part103.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part103.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part89.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part89.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part82.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part82.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part111.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part111.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part115.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part115.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part131.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part131.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part94.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part94.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part71.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part71.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part22.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part22.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part34.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part34.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part76.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part76.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part126.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part126.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part41.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part41.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part27.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part27.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part3.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part3.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part67.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part67.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part24.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part24.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part117.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part117.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part5.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part5.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part127.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part127.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part81.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part81.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part7.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part7.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part18.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part18.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part6.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part6.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part108.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part108.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part55.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part55.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part9.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part9.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part119.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part119.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part106.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part106.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part130.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part130.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part25.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part25.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part53.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part53.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part72.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part72.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part42.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part42.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part93.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part93.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part30.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part30.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part32.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part32.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part26.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part26.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part25.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part25.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part1.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part1.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part16.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part16.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part43.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part43.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part1.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part1.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part58.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part58.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part73.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part73.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part113.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part113.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part52.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part52.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part12.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part12.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part83.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part83.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part16.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part16.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part97.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part97.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part79.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part79.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part113.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part113.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part84.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part84.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part77.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part77.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part0.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part0.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part112.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part112.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part18.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part18.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part56.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part56.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part98.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part98.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part19.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part19.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part85.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part85.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part4.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part4.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part107.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part107.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part66.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part66.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part102.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part102.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part8.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part8.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part31.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part31.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part47.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part47.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part50.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part50.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part88.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part88.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part7.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part7.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part86.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part86.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part21.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part21.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part26.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part26.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part65.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part65.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part6.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part6.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part75.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part75.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part119.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part119.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part94.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part94.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part57.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part57.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part50.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part50.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part76.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part76.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part121.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part121.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part64.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part64.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part100.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part100.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part58.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part58.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part100.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part100.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part27.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part27.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part45.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part45.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part15.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part15.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part95.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part95.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part118.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part118.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part74.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part74.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part97.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part97.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part46.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part46.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part101.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part101.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part20.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part20.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part46.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part46.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part13.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part13.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part87.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part87.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part0.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part0.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part14.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part14.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part14.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part14.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part71.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part71.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part4.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part4.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part90.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part90.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part34.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part34.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part43.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part43.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part34.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part34.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part95.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part95.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part110.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part110.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part2.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part2.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part35.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part35.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part124.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part124.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part25.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part25.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part26.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part26.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part92.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part92.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part11.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part11.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part73.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part73.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part3.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part3.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part61.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part61.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part23.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part23.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part70.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part70.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part51.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part51.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part85.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part85.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part122.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part122.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part28.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part28.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part53.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part53.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part60.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part60.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part104.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part104.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part72.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part72.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part2.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part2.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part93.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part93.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part96.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part96.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part66.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part66.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part36.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part36.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part10.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part10.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part83.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part83.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part17.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part17.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part21.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part21.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part36.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part36.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part62.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part62.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part51.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part51.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part10.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part10.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part101.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part101.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part65.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part65.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part20.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part20.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part10.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part10.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part9.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part9.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part23.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part23.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part105.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part105.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part30.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part30.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part81.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part81.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part27.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part27.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part12.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part12.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part39.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part39.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part68.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part68.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part98.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part98.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part112.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part112.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part45.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part45.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part19.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part19.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part77.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part77.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part80.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part80.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part63.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part63.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part20.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part20.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part8.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part8.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part123.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part123.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part44.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part44.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part33.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part33.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part116.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part116.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part33.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part33.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part29.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part29.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part12.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part12.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part5.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part5.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part17.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part17.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part92.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part92.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part9.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part9.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part5.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part5.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part38.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part38.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part62.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part62.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part106.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part106.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part117.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part117.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part102.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part102.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part120.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part120.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part103.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part103.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part17.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part17.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part88.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part88.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part84.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part84.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part18.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part18.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part68.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part68.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part49.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part49.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part107.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part107.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part63.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part63.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part0.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part0.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part104.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part104.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part35.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part35.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part54.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part54.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part89.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part89.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part3.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part3.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part116.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part116.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part21.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part21.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part31.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part31.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part69.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part69.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part4.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part4.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part86.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part86.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part59.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part59.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part132.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part132.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part31.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part31.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part48.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part48.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part56.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part56.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part37.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part37.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part125.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part125.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part74.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part74.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part13.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part13.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part40.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part40.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part82.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part82.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part67.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part67.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part37.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part37.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part16.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part16.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part24.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part24.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part28.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part28.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part64.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part64.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part52.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part52.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part33.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part33.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part32.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part32.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part90.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part90.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part42.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part42.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part79.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part79.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part60.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part60.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part8.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part8.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part23.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part23.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part78.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part78.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part59.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part59.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part35.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part35.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part57.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part57.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part80.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part80.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part30.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part30.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part39.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part39.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part105.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part105.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part99.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part99.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part15.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part15.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part87.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part87.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part96.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part96.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part120.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part120.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part54.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part54.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part75.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part75.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part24.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part24.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part108.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part108.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part14.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part14.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part2.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part2.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part111.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part111.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part133.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part133.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part29.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part29.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part48.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part48.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part91.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part91.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part91.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part91.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part70.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part70.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part22.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part22.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part69.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part69.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part61.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part61.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part114.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part114.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part28.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part28.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part41.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part41.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part110.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part110.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part129.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part129.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part38.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part38.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part6.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part6.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part19.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part19.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part44.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part44.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part49.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part49.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part128.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part128.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part99.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part99.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part114.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part114.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part78.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part78.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part13.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part13.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part109.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part109.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part32.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part32.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part15.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part15.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part55.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part55.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part118.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part118.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part109.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part109.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part7.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part7.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part1.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_TTToSemiLeptonic__part1.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part115.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_DYJetsToLL_M-50__part115.root  ele
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part47.root  mu
bsub -q 2nd -u alvareza submit_batch_FR.sh nanoLatino_WJetsToLNu-LO__part47.root  ele
